// Comprehensive Seed Dataset for Property Hub & BachelorHub Ecosystem

const initialProperties = [
  {
    customId: "PROP-1001",
    title: "Premium 2 BHK Furnished Flat Gomti Nagar",
    type: "Flat",
    listingType: "Rent",
    price: 18500,
    priceUnit: "/month",
    deposit: 37000,
    bhk: 2,
    areaSqFt: 1150,
    address: "Vipul Khand 3, Near City Mall, Gomti Nagar",
    locality: "Gomti Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Vikramaditya Roy",
    ownerPhone: "+91 98390 12845",
    ownerRole: "Direct Owner",
    amenities: ["Power Backup", "Lift", "Security", "Water Supply", "Covered Car Parking"],
    furnishing: "Furnished",
    targetTenant: "Bachelors & Working Singles",
    description: "Fully furnished 2 BHK flat for working IT professionals or students.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 342
  },
  {
    customId: "PROP-1002",
    title: "Spacious Independent 3 BHK Villa with Garden",
    type: "House",
    listingType: "Rent",
    price: 32000,
    priceUnit: "/month",
    deposit: 64000,
    bhk: 3,
    areaSqFt: 2200,
    address: "Sector B, Aliganj, Near Kendriya Vidyalaya",
    locality: "Aliganj",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Ananya Deshmukh",
    ownerPhone: "+91 94150 88219",
    ownerRole: "Direct Owner",
    amenities: ["Private Garden", "Servant Room", "Power Backup", "Borewell Water"],
    furnishing: "Semi-Furnished",
    targetTenant: "Family & Senior Executives",
    description: "Independent luxury house with car porch and garden.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 520
  },
  {
    customId: "PROP-1003",
    title: "1 BHK Studio Flat for Students near Polytechnic",
    type: "Flat",
    listingType: "Rent",
    price: 8500,
    priceUnit: "/month",
    deposit: 8500,
    bhk: 1,
    areaSqFt: 550,
    address: "Sector 14, Indira Nagar, Ring Road",
    locality: "Indira Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Deepak Srivastava",
    ownerPhone: "+91 99190 44332",
    ownerRole: "Direct Owner",
    amenities: ["Wi-Fi Ready", "Water Filter", "Single Bed Included"],
    furnishing: "Furnished",
    targetTenant: "Students & Bachelors Only",
    description: "Affordable room with private washroom and balcony.",
    status: "Pending Verification",
    reportsCount: 0,
    viewsCount: 88
  },
  {
    customId: "PROP-1004",
    title: "Bachelor PG Sharing Beds with Food & Wi-Fi",
    type: "PG",
    listingType: "Rent",
    price: 6500,
    priceUnit: "/bed/mo",
    deposit: 6500,
    bhk: 1,
    areaSqFt: 350,
    address: "Engineering College Chauraha, Jankipuram",
    locality: "Jankipuram",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Rajesh Kumar Awasthi",
    ownerPhone: "+91 98380 77112",
    ownerRole: "Direct Owner",
    amenities: ["3 Times Mess Food", "RO Water", "Wi-Fi", "Daily Cleaning", "CCTV"],
    furnishing: "Furnished",
    targetTenant: "College Students (Boys)",
    description: "Top rated hostel style bachelor sharing room near AKTU college.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 215
  },
  {
    customId: "PROP-1005",
    title: "Luxury 3 BHK High-Rise Penthouse with Rooftop",
    type: "Flat",
    listingType: "Rent",
    price: 45000,
    priceUnit: "/month",
    deposit: 90000,
    bhk: 3,
    areaSqFt: 2600,
    address: "Tower 4, Shalimar Grand Residences, Hazratganj",
    locality: "Hazratganj",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Harshvardhan Kapoor",
    ownerPhone: "+91 94500 99881",
    ownerRole: "Commercial Owner",
    amenities: ["Swimming Pool", "Club House", "Gym", "Concierge 24x7", "EV Charger"],
    furnishing: "Furnished",
    targetTenant: "Corporate Expats & High Net Worth",
    description: "Ultra luxury residential penthouse with panoramic skyline views of Central Lucknow.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 780
  },
  {
    customId: "PROP-1006",
    title: "2 BHK Budget Apartment near Wave Mall",
    type: "Flat",
    listingType: "Rent",
    price: 14000,
    priceUnit: "/month",
    deposit: 28000,
    bhk: 2,
    areaSqFt: 980,
    address: "Vibhuti Khand, Phase 2, Near Wave Multiplex",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: true,
    duplicateScore: "94% Match with PROP-1001",
    ownerName: "Amitabh Nigam (Broker)",
    ownerPhone: "+91 87650 33211",
    ownerRole: "Broker",
    amenities: ["Car Parking", "Security Guard", "Lift"],
    furnishing: "Semi-Furnished",
    targetTenant: "Anyone",
    description: "Affordable flat close to IT park and Cyber heights.",
    status: "Pending Verification",
    reportsCount: 1,
    viewsCount: 45
  },
  {
    customId: "PROP-1007",
    title: "Commercial Office Floor for Startups & IT Firms",
    type: "Office",
    listingType: "Rent",
    price: 65000,
    priceUnit: "/month",
    deposit: 195000,
    bhk: 0,
    areaSqFt: 3500,
    address: "Cyber Heights, 5th Floor, Vibhuti Khand",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Harshvardhan Kapoor",
    ownerPhone: "+91 94500 99881",
    ownerRole: "Commercial Owner",
    amenities: ["High Speed Fiber", "Central AC", "100% DG Power Backup", "Visitor Lounge"],
    furnishing: "Furnished",
    targetTenant: "Corporates & Tech Startups",
    description: "Plug & play commercial tech office with 45 workstations and conference room.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 412
  },
  {
    customId: "PROP-1008",
    title: "Cozy 1 RK Studio Apartment for Girls",
    type: "Flat",
    listingType: "Rent",
    price: 9000,
    priceUnit: "/month",
    deposit: 9000,
    bhk: 1,
    areaSqFt: 480,
    address: "Mahanagar Gole Market, Near IT College",
    locality: "Mahanagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Sunita Mehrotra",
    ownerPhone: "+91 97920 66554",
    ownerRole: "Direct Owner",
    amenities: ["Gated Security", "CCTV on Floor", "Geyser", "Separate Kitchenette"],
    furnishing: "Furnished",
    targetTenant: "Single Female Professionals / Students",
    description: "Extremely safe and peaceful location with grocery shops right downstairs.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 310
  },
  {
    customId: "PROP-1009",
    title: "Brand New 2 BHK Builder Floor for Sale",
    type: "House",
    listingType: "Buy",
    price: 4800000,
    priceUnit: "Total",
    deposit: 500000,
    bhk: 2,
    areaSqFt: 1250,
    address: "Raebareli Road, Near SGPGIMS",
    locality: "Raebareli Road",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Vikramaditya Roy",
    ownerPhone: "+91 98390 12845",
    ownerRole: "Direct Owner",
    amenities: ["LDA Approved", "Bank Loan Available", "Modular Kitchen", "Dedicated Roof Rights"],
    furnishing: "Semi-Furnished",
    targetTenant: "Families & Investors",
    description: "LDA approved freehold residential builder floor with registry ready.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 620
  },
  {
    customId: "PROP-1010",
    title: "Spacious 4 BHK Independent Duplex Kothi",
    type: "House",
    listingType: "Rent",
    price: 42000,
    priceUnit: "/month",
    deposit: 84000,
    bhk: 4,
    areaSqFt: 3000,
    address: "Eldeco Greens, Gomti Nagar",
    locality: "Gomti Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Ananya Deshmukh",
    ownerPhone: "+91 94150 88219",
    ownerRole: "Direct Owner",
    amenities: ["Clubhouse Access", "Private Lawn", "Covered Garage", "Solar Inverter"],
    furnishing: "Furnished",
    targetTenant: "High Profile Families & Doctors",
    description: "Elite gated community duplex with modern imported fittings.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 430
  },
  {
    customId: "PROP-1011",
    title: "2 BHK Flat in Eldeco Elegante",
    type: "Flat",
    listingType: "Rent",
    price: 21000,
    priceUnit: "/month",
    deposit: 42000,
    bhk: 2,
    areaSqFt: 1300,
    address: "Vibhuti Khand, Gomti Nagar",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Deepak Srivastava",
    ownerPhone: "+91 99190 44332",
    ownerRole: "Direct Owner",
    amenities: ["Power Backup", "Gym", "Intercom", "Park Facing"],
    furnishing: "Semi-Furnished",
    targetTenant: "Families & Couples",
    description: "Well ventilated society flat with 2 spacious balconies.",
    status: "Pending Verification",
    reportsCount: 0,
    viewsCount: 75
  },
  {
    customId: "PROP-1012",
    title: "Single Room PG near BBD University",
    type: "PG",
    listingType: "Rent",
    price: 5500,
    priceUnit: "/month",
    deposit: 5500,
    bhk: 1,
    areaSqFt: 300,
    address: "Ayodhya Road, Near BBD Campus",
    locality: "Ayodhya Road",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Rajesh Kumar Awasthi",
    ownerPhone: "+91 98380 77112",
    ownerRole: "Direct Owner",
    amenities: ["Study Table & Chair", "Wi-Fi 100 Mbps", "Purified Water", "Bicycle Parking"],
    furnishing: "Furnished",
    targetTenant: "College Students",
    description: "Walking distance from BBD University campus gates.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 190
  }
];

const initialOwners = [
  {
    customId: "OWN-501",
    name: "Vikramaditya Roy",
    email: "vikram.roy@outlook.com",
    mobile: "+91 98390 12845",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "4521-8890-3412",
      pan: "ACUPR3498L",
      registry: "LDA Registered Sale Deed (Book 1, Vol 1420)",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar.pdf",
      panUrl: "/uploads/kyc/sample_pan.jpg",
      registryUrl: "/uploads/deeds/sample_deed.pdf"
    },
    propertiesCount: 4,
    status: "Active",
    remarks: "Official verified landlord badge granted. Excellent history."
  },
  {
    customId: "OWN-502",
    name: "Harshvardhan Kapoor",
    email: "harsh.kapoor@realtycorp.in",
    mobile: "+91 94500 99881",
    role: "Commercial Owner",
    kycStatus: "Pending",
    verificationStatus: "Pending",
    documents: {
      aadhaar: "8890-1123-5567",
      pan: "BZXPK9921M",
      registry: "Hazratganj Commercial Plaza Deed",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar2.pdf",
      panUrl: "/uploads/kyc/sample_pan2.jpg",
      registryUrl: "/uploads/deeds/sample_commercial_deed.pdf"
    },
    propertiesCount: 6,
    status: "Active",
    remarks: "Pending verification of commercial electricity bill and deed stamps."
  },
  {
    customId: "OWN-503",
    name: "Ananya Deshmukh",
    email: "ananya.deshmukh@gmail.com",
    mobile: "+91 94150 88219",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "3312-9901-4456",
      pan: "AQWPD1123K",
      registry: "Aliganj Independent Kothi Sale Certificate",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar3.pdf",
      panUrl: "/uploads/kyc/sample_pan3.jpg",
      registryUrl: "/uploads/deeds/sample_villa_deed.pdf"
    },
    propertiesCount: 3,
    status: "Active",
    remarks: "Verified direct owner. Clean title certificate."
  },
  {
    customId: "OWN-504",
    name: "Deepak Srivastava",
    email: "deepak.srivastava@yahoo.com",
    mobile: "+91 99190 44332",
    role: "Direct Owner",
    kycStatus: "Pending",
    verificationStatus: "Pending",
    documents: {
      aadhaar: "7765-2234-9012",
      pan: "CPQRS8821N",
      registry: "Indira Nagar Colony Allotment Paper",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar4.pdf",
      panUrl: "",
      registryUrl: "/uploads/deeds/sample_indira_nagar.pdf"
    },
    propertiesCount: 2,
    status: "Active",
    remarks: "PAN card copy requested."
  },
  {
    customId: "OWN-505",
    name: "Sunita Mehrotra",
    email: "sunita.mehrotra@gmail.com",
    mobile: "+91 97920 66554",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "9912-3345-7789",
      pan: "BHUPM4455Q",
      registry: "Mahanagar Gole Market Registry Deed",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar5.pdf",
      panUrl: "/uploads/kyc/sample_pan5.jpg",
      registryUrl: "/uploads/deeds/sample_mahanagar.pdf"
    },
    propertiesCount: 1,
    status: "Active",
    remarks: "Female landlord verified safe accommodations badge granted."
  }
];

const initialUsers = [
  {
    customId: "USR-101",
    name: "Aditya Verma",
    email: "aditya.verma@tcs.com",
    mobile: "+91 98890 23119",
    role: "Bachelor",
    city: "Lucknow",
    locality: "Gomti Nagar",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 14
  },
  {
    customId: "USR-102",
    name: "Pooja Sharma",
    email: "pooja.sharma@gmail.com",
    mobile: "+91 96500 88219",
    role: "Roommate",
    city: "Lucknow",
    locality: "Aliganj",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 6
  },
  {
    customId: "USR-103",
    name: "Rohan Tripathi",
    email: "rohan.tripathi@aktu.ac.in",
    mobile: "+91 94155 11200",
    role: "Bachelor",
    city: "Lucknow",
    locality: "Jankipuram",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 9
  },
  {
    customId: "USR-104",
    name: "Simran Kaur",
    email: "simran.kaur@hcl.com",
    mobile: "+91 99180 55432",
    role: "Tenant",
    city: "Lucknow",
    locality: "Hazratganj",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 3
  },
  {
    customId: "USR-105",
    name: "Manish Pandey",
    email: "manish.pandey@outlook.com",
    mobile: "+91 98399 77812",
    role: "Family",
    city: "Lucknow",
    locality: "Indira Nagar",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 11
  },
  {
    customId: "USR-106",
    name: "Alok Aggarwal",
    email: "alok.spam123@gmail.com",
    mobile: "+91 93350 11987",
    role: "Tenant",
    city: "Lucknow",
    locality: "Charbagh",
    status: "Suspended",
    reportsCount: 4,
    enquiriesSent: 28
  }
];

const initialTransactions = [
  {
    customId: "TXN-8001",
    userName: "Vikramaditya Roy",
    userRole: "Owner",
    purpose: "Featured Boost Plan (Gomti Nagar Flat)",
    amount: 999,
    gateway: "Razorpay",
    paymentId: "pay_Rzp902148Live",
    status: "Success"
  },
  {
    customId: "TXN-8002",
    userName: "Harshvardhan Kapoor",
    userRole: "Owner",
    purpose: "Commercial Landlord Pro Annual Subscription",
    amount: 4999,
    gateway: "Razorpay",
    paymentId: "pay_Rzp110294Live",
    status: "Success"
  },
  {
    customId: "TXN-8003",
    userName: "Ananya Deshmukh",
    userRole: "Owner",
    purpose: "Top Priority 30-Day Boost (Villa Listing)",
    amount: 1499,
    gateway: "Razorpay",
    paymentId: "pay_Rzp449012Live",
    status: "Success"
  },
  {
    customId: "TXN-8004",
    userName: "Aditya Verma",
    userRole: "Tenant",
    purpose: "Digital Rental Agreement e-Stamp Service",
    amount: 499,
    gateway: "Razorpay",
    paymentId: "pay_Rzp778120Live",
    status: "Success"
  },
  {
    customId: "TXN-8005",
    userName: "Rajesh Kumar Awasthi",
    userRole: "Owner",
    purpose: "PG Listing Featured Banner",
    amount: 799,
    gateway: "Razorpay",
    paymentId: "pay_Rzp331908Live",
    status: "Success"
  },
  {
    customId: "TXN-8006",
    userName: "Rohan Tripathi",
    userRole: "Bachelor",
    purpose: "Security Deposit Verification Shield",
    amount: 299,
    gateway: "Razorpay",
    paymentId: "pay_Rzp882143Live",
    status: "Success"
  }
];

const initialTickets = [
  {
    customId: "TKT-301",
    from: "Aditya Verma",
    phone: "+91 98890 23119",
    subject: "Owner not responding for scheduled visit at Gomti Nagar flat",
    category: "Visit Enquiry",
    priority: "Medium",
    status: "Open",
    details: "I booked a visit for Saturday 4 PM at PROP-1001, but landlord phone was switched off."
  },
  {
    customId: "TKT-302",
    from: "Harshvardhan Kapoor",
    phone: "+91 94500 99881",
    subject: "Commercial deed documents verification status inquiry",
    category: "KYC Verification",
    priority: "High",
    status: "In Progress",
    details: "Uploaded my Hazratganj commercial deed 48 hours ago. Please expedite approval."
  },
  {
    customId: "TKT-303",
    from: "Pooja Sharma",
    phone: "+91 96500 88219",
    subject: "Used furniture buyer cancelled without notification",
    category: "Used Marketplace",
    priority: "Low",
    status: "Resolved",
    details: "Buyer agreed on wooden table then stopped replying."
  },
  {
    customId: "TKT-304",
    from: "Sunita Mehrotra",
    phone: "+91 97920 66554",
    subject: "Need invoice copy for listing boost payment",
    category: "Payment / Refund",
    priority: "Medium",
    status: "Resolved",
    details: "GST invoice requested for tax filing purpose."
  },
  {
    customId: "TKT-305",
    from: "Rohan Tripathi",
    phone: "+91 94155 11200",
    subject: "App crashes when filtering rent below ₹6000",
    category: "Platform Bug",
    priority: "Urgent",
    status: "Open",
    details: "On Android, setting budget slider to minimum crashes the property search list."
  }
];

const initialServices = [
  {
    customId: "SRV-01",
    name: "Annapurna Homestyle Tiffin & Mess",
    category: "Tiffin / Mess",
    provider: "Manoj Tiwari",
    phone: "+91 98399 11001",
    rating: 4.8,
    orders: 840,
    priceStarts: "₹ 75 / meal",
    status: "Active",
    complaints: 1,
    verified: true
  },
  {
    customId: "SRV-02",
    name: "SpeedyWash Laundry & Dry Cleaners",
    category: "Laundry",
    provider: "Suresh Kashyap",
    phone: "+91 94150 22334",
    rating: 4.7,
    orders: 412,
    priceStarts: "₹ 15 / cloth",
    status: "Active",
    complaints: 0,
    verified: true
  },
  {
    customId: "SRV-03",
    name: "TrustMaid Verified Domestic Helpers",
    category: "House Maid",
    provider: "Sunita Maurya",
    phone: "+91 98399 22100",
    rating: 4.8,
    orders: 342,
    priceStarts: "₹ 1,499 / mo",
    status: "Active",
    complaints: 0,
    verified: true
  },
  {
    customId: "SRV-04",
    name: "QuickVolt Electrician & AC Repair",
    category: "Electrician",
    provider: "Anil Sharma",
    phone: "+91 97112 33445",
    rating: 4.6,
    orders: 520,
    priceStarts: "₹ 199",
    status: "Active",
    complaints: 1,
    verified: true
  },
  {
    customId: "SRV-05",
    name: "Express Fix Plumber & Sanitary",
    category: "Plumber",
    provider: "Dinesh Kumar",
    phone: "+91 87650 11928",
    rating: 4.6,
    orders: 219,
    priceStarts: "₹ 249",
    status: "Active",
    complaints: 0,
    verified: true
  },
  {
    customId: "SRV-06",
    name: "SafeShift Packers & Movers",
    category: "Packers & Movers",
    provider: "Rajesh Logistics",
    phone: "+91 94150 99881",
    rating: 4.9,
    orders: 512,
    priceStarts: "₹ 2,999",
    status: "Active",
    complaints: 3,
    verified: true
  }
];

const initialUsedItems = [
  {
    customId: "ITEM-301",
    title: "Solid Sheesham Wood Queen Bed with Storage",
    category: "Furniture",
    price: 11500,
    originalPrice: 24000,
    sellerName: "Tanmay Gupta (Tenant)",
    phone: "+91 98190 77123",
    locality: "Mahanagar, Lucknow",
    status: "Active",
    condition: "Like New (1 yr used)",
    reported: false,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=400&q=80"
  },
  {
    customId: "ITEM-302",
    title: "LG 260L 3-Star Inverter Frost-Free Refrigerator",
    category: "Appliances",
    price: 13500,
    originalPrice: 28000,
    sellerName: "Neha Rastogi",
    phone: "+91 94151 33445",
    locality: "Gomti Nagar, Lucknow",
    status: "Active",
    condition: "Good Condition",
    reported: false,
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=400&q=80"
  },
  {
    customId: "ITEM-303",
    title: "Ergonomic Mesh Study / Office Chair with Lumbar",
    category: "Furniture",
    price: 3200,
    originalPrice: 8500,
    sellerName: "Rohit Saxena",
    phone: "+91 93350 44556",
    locality: "Vibhuti Khand",
    status: "Reported",
    condition: "Broken armrest (Disputed description)",
    reported: true,
    image: "https://images.unsplash.com/photo-1580481077195-c3a821a58875?auto=format&fit=crop&w=400&q=80"
  },
  {
    customId: "ITEM-304",
    title: "Bajaj Majesty 16L Microwave Oven",
    category: "Appliances",
    price: 3800,
    originalPrice: 7500,
    sellerName: "Aditya Verma",
    phone: "+91 98890 23119",
    locality: "Indira Nagar",
    status: "Active",
    condition: "Excellent Condition",
    reported: false,
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=400&q=80"
  }
];

const initialVisits = [
  {
    customId: "VIS-401",
    propertyId: "PROP-1001",
    propertyTitle: "Premium 2 BHK Furnished Flat Gomti Nagar",
    locality: "Gomti Nagar",
    city: "Lucknow",
    visitorName: "Aditya Verma",
    visitorPhone: "+91 98890 23119",
    visitorEmail: "aditya.verma@tcs.com",
    ownerName: "Vikramaditya Roy",
    ownerPhone: "+91 98390 12845",
    slotDate: "Tomorrow, 11:30 AM",
    slotTime: "Morning (10:00 AM - 1:00 PM)",
    leadType: "Direct Bachelor",
    status: "Confirmed",
    passCode: "PH-VIS-4921",
    notes: "Visitor is software engineer at TCS Lucknow looking for immediate possession."
  },
  {
    customId: "VIS-402",
    propertyId: "PROP-1002",
    propertyTitle: "Spacious Independent 3 BHK Villa with Garden",
    locality: "Aliganj",
    city: "Lucknow",
    visitorName: "Sunita Mehrotra",
    visitorPhone: "+91 97920 66554",
    visitorEmail: "sunita.mehrotra@gmail.com",
    ownerName: "Ananya Deshmukh",
    ownerPhone: "+91 94150 88219",
    slotDate: "Friday, 04:00 PM",
    slotTime: "Evening (3:00 PM - 6:00 PM)",
    leadType: "Family / Couple",
    status: "Completed",
    passCode: "PH-VIS-8812",
    notes: "Site visit completed. Tenant requested rental agreement draft."
  },
  {
    customId: "VIS-403",
    propertyId: "PROP-1004",
    propertyTitle: "Bachelor PG Sharing Beds with Food & Wi-Fi",
    locality: "Jankipuram",
    city: "Lucknow",
    visitorName: "Rohan Tripathi",
    visitorPhone: "+91 94155 11200",
    visitorEmail: "rohan.aktu@gmail.com",
    ownerName: "Rajesh Kumar Awasthi",
    ownerPhone: "+91 98380 77112",
    slotDate: "Saturday, 10:00 AM",
    slotTime: "Morning (10:00 AM - 1:00 PM)",
    leadType: "Direct Bachelor",
    status: "Pending",
    passCode: "PH-VIS-3320",
    notes: "Student at Engineering College requesting mess food tasting during visit."
  },
  {
    customId: "VIS-404",
    propertyId: "PROP-1005",
    propertyTitle: "Luxury 3 BHK High-Rise Penthouse with Rooftop",
    locality: "Hazratganj",
    city: "Lucknow",
    visitorName: "Deepak Srivastava",
    visitorPhone: "+91 99190 44332",
    visitorEmail: "deepak.srivastava@yahoo.com",
    ownerName: "Harshvardhan Kapoor",
    ownerPhone: "+91 94500 99881",
    slotDate: "Sunday, 05:30 PM",
    slotTime: "Evening (3:00 PM - 6:00 PM)",
    leadType: "Corporate Tenant",
    status: "Confirmed",
    passCode: "PH-VIS-9941",
    notes: "Executive company lease inquiry."
  }
];

const initialRoommates = [
  {
    customId: "RM-101",
    userName: "Amit Kumar",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80",
    phone: "+91 98765 11223",
    email: "amit.kumar@hcl.com",
    gender: "Male",
    lookingFor: "Male Flatmate",
    budget: 6500,
    targetLocality: "Gomti Nagar",
    city: "Lucknow",
    profession: "Software Engineer @ HCL",
    bio: "Working at HCL Lucknow. Looking for a clean, chill, and friendly flatmate who respects privacy.",
    tags: ["Non-Smoker", "Veg / Non-Veg", "Night Owl", "Clean Space"],
    status: "Active"
  },
  {
    customId: "RM-102",
    userName: "Rahul Singh",
    userAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80",
    phone: "+91 94155 33445",
    email: "rahul.ias@gmail.com",
    gender: "Male",
    lookingFor: "1 Room in 2BHK / 3BHK Flat",
    budget: 7500,
    targetLocality: "Aliganj",
    city: "Lucknow",
    profession: "Govt. Job Aspirant (UPSC)",
    bio: "Preparing for civil services. Need a peaceful, studious environment with disciplined roommates.",
    tags: ["Pure Veg", "Non-Smoker", "Quiet Environment", "Early Riser"],
    status: "Active"
  },
  {
    customId: "RM-103",
    userName: "Priya Sharma",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    phone: "+91 99188 66778",
    email: "priya.designs@gmail.com",
    gender: "Female",
    lookingFor: "Female Flatmate",
    budget: 8000,
    targetLocality: "Indira Nagar",
    city: "Lucknow",
    profession: "UI/UX Product Designer",
    bio: "Working remotely for a tech company. Friendly, loves indie music, and keeps common spaces neat.",
    tags: ["Female Only", "Non-Smoker", "Pet Friendly", "Remote Worker"],
    status: "Active"
  },
  {
    customId: "RM-104",
    userName: "Vikas Awasthi",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    phone: "+91 98390 55432",
    email: "vikas.banking@gmail.com",
    gender: "Male",
    lookingFor: "Male Flatmate",
    budget: 5500,
    targetLocality: "Mahanagar",
    city: "Lucknow",
    profession: "Bank Probationary Officer",
    bio: "Recently transferred to Lucknow SBI branch. Simple and friendly person looking to share rent.",
    tags: ["Working Pro", "Non-Smoker", "Weekend Traveler"],
    status: "Active"
  }
];

module.exports = {
  initialProperties,
  initialOwners,
  initialUsers,
  initialTransactions,
  initialTickets,
  initialServices,
  initialUsedItems,
  initialVisits,
  initialRoommates
};
