// Comprehensive Seed Dataset for Property Hub & BachelorHub Ecosystem

const initialProperties = [
  {
    customId: "PROP-1001",
    title: "Premium 2 BHK Furnished Flat Gomti Nagar",
    type: "Flat",
    listingType: "Rent",
    price: 18500,
    priceUnit: "/month",
    deposit: 37000,
    bhk: 2,
    areaSqFt: 1150,
    address: "Vipul Khand 3, Near City Mall, Gomti Nagar",
    locality: "Gomti Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Vikramaditya Roy",
    ownerPhone: "+91 98390 12845",
    ownerRole: "Direct Owner",
    amenities: ["Power Backup", "Lift", "Security", "Water Supply", "Covered Car Parking"],
    furnishing: "Furnished",
    targetTenant: "Bachelors & Working Singles",
    description: "Fully furnished 2 BHK flat for working IT professionals or students.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 342
  },
  {
    customId: "PROP-1002",
    title: "Spacious Independent 3 BHK Villa with Garden",
    type: "House",
    listingType: "Rent",
    price: 32000,
    priceUnit: "/month",
    deposit: 64000,
    bhk: 3,
    areaSqFt: 2200,
    address: "Sector B, Aliganj, Near Kendriya Vidyalaya",
    locality: "Aliganj",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Ananya Deshmukh",
    ownerPhone: "+91 94150 88219",
    ownerRole: "Direct Owner",
    amenities: ["Private Garden", "Servant Room", "Power Backup", "Borewell Water"],
    furnishing: "Semi-Furnished",
    targetTenant: "Family & Senior Executives",
    description: "Independent luxury house with car porch and garden.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 520
  },
  {
    customId: "PROP-1003",
    title: "1 BHK Studio Flat for Students near Polytechnic",
    type: "Flat",
    listingType: "Rent",
    price: 8500,
    priceUnit: "/month",
    deposit: 8500,
    bhk: 1,
    areaSqFt: 550,
    address: "Sector 14, Indira Nagar, Ring Road",
    locality: "Indira Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Deepak Srivastava",
    ownerPhone: "+91 99190 44332",
    ownerRole: "Direct Owner",
    amenities: ["Wi-Fi Ready", "Water Filter", "Single Bed Included"],
    furnishing: "Furnished",
    targetTenant: "Students & Bachelors Only",
    description: "Affordable room with private washroom and balcony.",
    status: "Pending Verification",
    reportsCount: 0,
    viewsCount: 88
  },
  {
    customId: "PROP-1004",
    title: "Bachelor PG Sharing Beds with Food & Wi-Fi",
    type: "PG",
    listingType: "Rent",
    price: 6500,
    priceUnit: "/bed/mo",
    deposit: 6500,
    bhk: 1,
    areaSqFt: 350,
    address: "Engineering College Chauraha, Jankipuram",
    locality: "Jankipuram",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Rajesh Kumar Awasthi",
    ownerPhone: "+91 98380 77112",
    ownerRole: "Direct Owner",
    amenities: ["3 Times Mess Food", "RO Water", "Wi-Fi", "Daily Cleaning", "CCTV"],
    furnishing: "Furnished",
    targetTenant: "College Students (Boys)",
    description: "Top rated hostel style bachelor sharing room near AKTU college.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 215
  },
  {
    customId: "PROP-1005",
    title: "Luxury 3 BHK High-Rise Penthouse with Rooftop",
    type: "Flat",
    listingType: "Rent",
    price: 45000,
    priceUnit: "/month",
    deposit: 90000,
    bhk: 3,
    areaSqFt: 2600,
    address: "Tower 4, Shalimar Grand Residences, Hazratganj",
    locality: "Hazratganj",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Harshvardhan Kapoor",
    ownerPhone: "+91 94500 99881",
    ownerRole: "Commercial Owner",
    amenities: ["Swimming Pool", "Club House", "Gym", "Concierge 24x7", "EV Charger"],
    furnishing: "Furnished",
    targetTenant: "Corporate Expats & High Net Worth",
    description: "Ultra luxury residential penthouse with panoramic skyline views of Central Lucknow.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 780
  },
  {
    customId: "PROP-1006",
    title: "2 BHK Budget Apartment near Wave Mall",
    type: "Flat",
    listingType: "Rent",
    price: 14000,
    priceUnit: "/month",
    deposit: 28000,
    bhk: 2,
    areaSqFt: 980,
    address: "Vibhuti Khand, Phase 2, Near Wave Multiplex",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: true,
    duplicateScore: "94% Match with PROP-1001",
    ownerName: "Amitabh Nigam (Broker)",
    ownerPhone: "+91 87650 33211",
    ownerRole: "Broker",
    amenities: ["Car Parking", "Security Guard", "Lift"],
    furnishing: "Semi-Furnished",
    targetTenant: "Anyone",
    description: "Affordable flat close to IT park and Cyber heights.",
    status: "Pending Verification",
    reportsCount: 1,
    viewsCount: 45
  },
  {
    customId: "PROP-1007",
    title: "Commercial Office Floor for Startups & IT Firms",
    type: "Office",
    listingType: "Rent",
    price: 65000,
    priceUnit: "/month",
    deposit: 195000,
    bhk: 0,
    areaSqFt: 3500,
    address: "Cyber Heights, 5th Floor, Vibhuti Khand",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Harshvardhan Kapoor",
    ownerPhone: "+91 94500 99881",
    ownerRole: "Commercial Owner",
    amenities: ["High Speed Fiber", "Central AC", "100% DG Power Backup", "Visitor Lounge"],
    furnishing: "Furnished",
    targetTenant: "Corporates & Tech Startups",
    description: "Plug & play commercial tech office with 45 workstations and conference room.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 412
  },
  {
    customId: "PROP-1008",
    title: "Cozy 1 RK Studio Apartment for Girls",
    type: "Flat",
    listingType: "Rent",
    price: 9000,
    priceUnit: "/month",
    deposit: 9000,
    bhk: 1,
    areaSqFt: 480,
    address: "Mahanagar Gole Market, Near IT College",
    locality: "Mahanagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Sunita Mehrotra",
    ownerPhone: "+91 97920 66554",
    ownerRole: "Direct Owner",
    amenities: ["Gated Security", "CCTV on Floor", "Geyser", "Separate Kitchenette"],
    furnishing: "Furnished",
    targetTenant: "Single Female Professionals / Students",
    description: "Extremely safe and peaceful location with grocery shops right downstairs.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 310
  },
  {
    customId: "PROP-1009",
    title: "Brand New 2 BHK Builder Floor for Sale",
    type: "House",
    listingType: "Buy",
    price: 4800000,
    priceUnit: "Total",
    deposit: 500000,
    bhk: 2,
    areaSqFt: 1250,
    address: "Raebareli Road, Near SGPGIMS",
    locality: "Raebareli Road",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Vikramaditya Roy",
    ownerPhone: "+91 98390 12845",
    ownerRole: "Direct Owner",
    amenities: ["LDA Approved", "Bank Loan Available", "Modular Kitchen", "Dedicated Roof Rights"],
    furnishing: "Semi-Furnished",
    targetTenant: "Families & Investors",
    description: "LDA approved freehold residential builder floor with registry ready.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 620
  },
  {
    customId: "PROP-1010",
    title: "Spacious 4 BHK Independent Duplex Kothi",
    type: "House",
    listingType: "Rent",
    price: 42000,
    priceUnit: "/month",
    deposit: 84000,
    bhk: 4,
    areaSqFt: 3000,
    address: "Eldeco Greens, Gomti Nagar",
    locality: "Gomti Nagar",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: true,
    isDuplicate: false,
    ownerName: "Ananya Deshmukh",
    ownerPhone: "+91 94150 88219",
    ownerRole: "Direct Owner",
    amenities: ["Clubhouse Access", "Private Lawn", "Covered Garage", "Solar Inverter"],
    furnishing: "Furnished",
    targetTenant: "High Profile Families & Doctors",
    description: "Elite gated community duplex with modern imported fittings.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 430
  },
  {
    customId: "PROP-1011",
    title: "2 BHK Flat in Eldeco Elegante",
    type: "Flat",
    listingType: "Rent",
    price: 21000,
    priceUnit: "/month",
    deposit: 42000,
    bhk: 2,
    areaSqFt: 1300,
    address: "Vibhuti Khand, Gomti Nagar",
    locality: "Vibhuti Khand",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: false,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Deepak Srivastava",
    ownerPhone: "+91 99190 44332",
    ownerRole: "Direct Owner",
    amenities: ["Power Backup", "Gym", "Intercom", "Park Facing"],
    furnishing: "Semi-Furnished",
    targetTenant: "Families & Couples",
    description: "Well ventilated society flat with 2 spacious balconies.",
    status: "Pending Verification",
    reportsCount: 0,
    viewsCount: 75
  },
  {
    customId: "PROP-1012",
    title: "Single Room PG near BBD University",
    type: "PG",
    listingType: "Rent",
    price: 5500,
    priceUnit: "/month",
    deposit: 5500,
    bhk: 1,
    areaSqFt: 300,
    address: "Ayodhya Road, Near BBD Campus",
    locality: "Ayodhya Road",
    city: "Lucknow",
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=900&q=80"
    ],
    isVerified: true,
    isFeatured: false,
    isDuplicate: false,
    ownerName: "Rajesh Kumar Awasthi",
    ownerPhone: "+91 98380 77112",
    ownerRole: "Direct Owner",
    amenities: ["Study Table & Chair", "Wi-Fi 100 Mbps", "Purified Water", "Bicycle Parking"],
    furnishing: "Furnished",
    targetTenant: "College Students",
    description: "Walking distance from BBD University campus gates.",
    status: "Active",
    reportsCount: 0,
    viewsCount: 190
  }
];

const initialOwners = [
  {
    customId: "OWN-501",
    name: "Vikramaditya Roy",
    email: "vikram.roy@outlook.com",
    mobile: "+91 98390 12845",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "4521-8890-3412",
      pan: "ACUPR3498L",
      registry: "LDA Registered Sale Deed (Book 1, Vol 1420)",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar.pdf",
      panUrl: "/uploads/kyc/sample_pan.jpg",
      registryUrl: "/uploads/deeds/sample_deed.pdf"
    },
    propertiesCount: 4,
    status: "Active",
    remarks: "Official verified landlord badge granted. Excellent history."
  },
  {
    customId: "OWN-502",
    name: "Harshvardhan Kapoor",
    email: "harsh.kapoor@realtycorp.in",
    mobile: "+91 94500 99881",
    role: "Commercial Owner",
    kycStatus: "Pending",
    verificationStatus: "Pending",
    documents: {
      aadhaar: "8890-1123-5567",
      pan: "BZXPK9921M",
      registry: "Hazratganj Commercial Plaza Deed",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar2.pdf",
      panUrl: "/uploads/kyc/sample_pan2.jpg",
      registryUrl: "/uploads/deeds/sample_commercial_deed.pdf"
    },
    propertiesCount: 6,
    status: "Active",
    remarks: "Pending verification of commercial electricity bill and deed stamps."
  },
  {
    customId: "OWN-503",
    name: "Ananya Deshmukh",
    email: "ananya.deshmukh@gmail.com",
    mobile: "+91 94150 88219",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "3312-9901-4456",
      pan: "AQWPD1123K",
      registry: "Aliganj Independent Kothi Sale Certificate",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar3.pdf",
      panUrl: "/uploads/kyc/sample_pan3.jpg",
      registryUrl: "/uploads/deeds/sample_villa_deed.pdf"
    },
    propertiesCount: 3,
    status: "Active",
    remarks: "Verified direct owner. Clean title certificate."
  },
  {
    customId: "OWN-504",
    name: "Deepak Srivastava",
    email: "deepak.srivastava@yahoo.com",
    mobile: "+91 99190 44332",
    role: "Direct Owner",
    kycStatus: "Pending",
    verificationStatus: "Pending",
    documents: {
      aadhaar: "7765-2234-9012",
      pan: "CPQRS8821N",
      registry: "Indira Nagar Colony Allotment Paper",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar4.pdf",
      panUrl: "",
      registryUrl: "/uploads/deeds/sample_indira_nagar.pdf"
    },
    propertiesCount: 2,
    status: "Active",
    remarks: "PAN card copy requested."
  },
  {
    customId: "OWN-505",
    name: "Sunita Mehrotra",
    email: "sunita.mehrotra@gmail.com",
    mobile: "+91 97920 66554",
    role: "Direct Owner",
    kycStatus: "Verified",
    verificationStatus: "Approved",
    documents: {
      aadhaar: "9912-3345-7789",
      pan: "BHUPM4455Q",
      registry: "Mahanagar Gole Market Registry Deed",
      aadhaarUrl: "/uploads/kyc/sample_aadhaar5.pdf",
      panUrl: "/uploads/kyc/sample_pan5.jpg",
      registryUrl: "/uploads/deeds/sample_mahanagar.pdf"
    },
    propertiesCount: 1,
    status: "Active",
    remarks: "Female landlord verified safe accommodations badge granted."
  }
];

const initialUsers = [
  {
    customId: "USR-101",
    name: "Aditya Verma",
    email: "aditya.verma@tcs.com",
    mobile: "+91 98890 23119",
    role: "Bachelor",
    city: "Lucknow",
    locality: "Gomti Nagar",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 14
  },
  {
    customId: "USR-102",
    name: "Pooja Sharma",
    email: "pooja.sharma@gmail.com",
    mobile: "+91 96500 88219",
    role: "Roommate",
    city: "Lucknow",
    locality: "Aliganj",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 6
  },
  {
    customId: "USR-103",
    name: "Rohan Tripathi",
    email: "rohan.tripathi@aktu.ac.in",
    mobile: "+91 94155 11200",
    role: "Bachelor",
    city: "Lucknow",
    locality: "Jankipuram",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 9
  },
  {
    customId: "USR-104",
    name: "Simran Kaur",
    email: "simran.kaur@hcl.com",
    mobile: "+91 99180 55432",
    role: "Tenant",
    city: "Lucknow",
    locality: "Hazratganj",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 3
  },
  {
    customId: "USR-105",
    name: "Manish Pandey",
    email: "manish.pandey@outlook.com",
    mobile: "+91 98399 77812",
    role: "Family",
    city: "Lucknow",
    locality: "Indira Nagar",
    status: "Active",
    reportsCount: 0,
    enquiriesSent: 11
  },
  {
    customId: "USR-106",
    name: "Alok Aggarwal",
    email: "alok.spam123@gmail.com",
    mobile: "+91 93350 11987",
    role: "Tenant",
    city: "Lucknow",
    locality: "Charbagh",
    status: "Suspended",
    reportsCount: 4,
    enquiriesSent: 28
  }
];

const initialTransactions = [
  {
    customId: "TXN-8001",
    userName: "Vikramaditya Roy",
    userRole: "Owner",
    purpose: "Featured Boost Plan (Gomti Nagar Flat)",
    amount: 999,
    gateway: "Razorpay",
    paymentId: "pay_Rzp902148Live",
    status: "Success"
  },
  {
    customId: "TXN-8002",
    userName: "Harshvardhan Kapoor",
    userRole: "Owner",
    purpose: "Commercial Landlord Pro Annual Subscription",
    amount: 4999,
    gateway: "Razorpay",
    paymentId: "pay_Rzp110294Live",
    status: "Success"
  },
  {
    customId: "TXN-8003",
    userName: "Ananya Deshmukh",
    userRole: "Owner",
    purpose: "Top Priority 30-Day Boost (Villa Listing)",
    amount: 1499,
    gateway: "Razorpay",
    paymentId: "pay_Rzp449012Live",
    status: "Success"
  },
  {
    customId: "TXN-8004",
    userName: "Aditya Verma",
    userRole: "Tenant",
    purpose: "Digital Rental Agreement e-Stamp Service",
    amount: 499,
    gateway: "Razorpay",
    paymentId: "pay_Rzp778120Live",
    status: "Success"
  },
  {
    customId: "TXN-8005",
    userName: "Rajesh Kumar Awasthi",
    userRole: "Owner",
    purpose: "PG Listing Featured Banner",
    amount: 799,
    gateway: "Razorpay",
    paymentId: "pay_Rzp331908Live",
    status: "Success"
  },
  {
    customId: "TXN-8006",
    userName: "Rohan Tripathi",
    userRole: "Bachelor",
    purpose: "Security Deposit Verification Shield",
    amount: 299,
    gateway: "Razorpay",
    paymentId: "pay_Rzp882143Live",
    status: "Success"
  }
];

const initialTickets = [
  {
    customId: "TKT-301",
    from: "Aditya Verma",
    phone: "+91 98890 23119",
    subject: "Owner not responding for scheduled visit at Gomti Nagar flat",
    category: "Visit Enquiry",
    priority: "Medium",
    status: "Open",
    details: "I booked a visit for Saturday 4 PM at PROP-1001, but landlord phone was switched off."
  },
  {
    customId: "TKT-302",
    from: "Harshvardhan Kapoor",
    phone: "+91 94500 99881",
    subject: "Commercial deed documents verification status inquiry",
    category: "KYC Verification",
    priority: "High",
    status: "In Progress",
    details: "Uploaded my Hazratganj commercial deed 48 hours ago. Please expedite approval."
  },
  {
    customId: "TKT-303",
    from: "Pooja Sharma",
    phone: "+91 96500 88219",
    subject: "Used furniture buyer cancelled without notification",
    category: "Used Marketplace",
    priority: "Low",
    status: "Resolved",
    details: "Buyer agreed on wooden table then stopped replying."
  },
  {
    customId: "TKT-304",
    from: "Sunita Mehrotra",
    phone: "+91 97920 66554",
    subject: "Need invoice copy for listing boost payment",
    category: "Payment / Refund",
    priority: "Medium",
    status: "Resolved",
    details: "GST invoice requested for tax filing purpose."
  },
  {
    customId: "TKT-305",
    from: "Rohan Tripathi",
    phone: "+91 94155 11200",
    subject: "App crashes when filtering rent below ₹6000",
    category: "Platform Bug",
    priority: "Urgent",
    status: "Open",
    details: "On Android, setting budget slider to minimum crashes the property search list."
  }
];

module.exports = {
  initialProperties,
  initialOwners,
  initialUsers,
  initialTransactions,
  initialTickets
};
